#这是一个toml配置示例

[server]                                        #服务器配置信息
    logFile = "d:\\wechatman.log"               #日志文件地址
    port = 9999                                 #服务器监听端口

[redis]                                         #redis 链接信息
    host = "127.0.0.1:3379"
    user = "root"
    password = "user"
    database = 1

[security]
    apiSignKey = "wechatServerSignKey"              #请求接口的校验签名key
    adminIpList = ["127.0.0.1"]                     #管理员ip地址，该地址可以请求配置文件重载等高权限操作
    adminToken = "adminToken"                       #管理员请求token
    useIpWhiteList = false                          #是否使用接口ip白名单
    ipList = ["127.0.0.1"]                          #普通请求的ip白名单

[wechatPublic]                                           #微信公众号配置
    appID = "wx55305d4efcc3d10c"                         #微信公众号或者小程序的appid
    appSecret = "f2aa62de4ce4b524b93e44c5199eed80"       #appsecret
    token = "wechatman"                                  #查询accessToken时提供的认证参数
    notifyUrl = ["http://localhost"]                     #该微信accessToken更新后，会请求该url列表中的地址
    encodeAesKey = ""                                    #消息加解密秘钥
    aheadTime = 600                                      #微信过期时间更新单位秒(s)
    loopTime = 60                                        #循环检测微信accesstoken是否过期的间隔秒(s)

[miniProgram]                                            #微信小程序配置


[wechatWeb]                                              #微信开发平台网站应用

